# Site settings
title: Multinexo Developers
version: 0.0.23
email: info@multinexo.com
description: >
  Documentación de la API de Multinexo. Sistema online de gestión para pequeñas y
  medianas empresas. Impresora fiscal, factura electrónica, stock,
  cuentas corrientes, multiusuario, ¡y más!
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://dev.multinexo.com # the base hostname & protocol for your site
git_address: https://github.com/multinexo
git_edit_address: https://github.com/multinexo/docs/blob/gh-pages

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - bitbucket-pipelines.yml
  - README.md
# timezone: america/argentina/mendoza

defaults:
# - scope:
#    path: _posts
#    type: posts
#  values:
#    layout: post
#    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    permalink: /:collection/:path/
    sectionid: docs

- scope:
    path: _styleguide
    type: styleguide
  values:
    layout: docs
    sectionid: styleguide
    seo:
      type: "WebPage"

collections:
  docs:
    # permalink: /:collection/:path/
    output: true

  styleguide:
    permalink: /styleguide/:title/
    output: true

sass:
  sass_dir: _sass
